### PR TITLE
update icon resolutions

### PR DESCRIPTION
**Pull request by willingc**
- updates icon resolution to 2x at 36dp
- includes other resolutions as well

### CODE REVIEW

**Comment by willingc** [comment]
screenshot 2018-12-07 11 50 00

screenshot 2018-12-07 11 50 12

**Comment by willingc** [comment]
CSS will need some tweaks. Let me know if you like the color or not.

**Comment by labarba** [comment]
Much prefer to keep it simple, without colors for the boxes.

**Comment by dsblank** [comment]
Very nice, @willingc ! The boxes either need a background, or a border. Looks really good.

**Comment by dsblank** [comment]
This looks good; ready to merge?

**Comment by labarba** [comment]
To see how this looks, do you guys build this locally, or what?

**Comment by dsblank** [comment]
I do: `make view-pdf` or `make view-html` There is another step in the process to deploy to see for sure everything works, but that requires the merge to gh-pages. It looks good BTW (grayscale backgrounds for now).

**Comment by willingc** [comment]
I was going to back out the colors for the standard grey. Just a bit busy early this week.

**Comment by willingc** [comment]
@labarba Yes, I build it locally.

It would be great to have something like zeit's now build that provides a link to a rendered version in the PR status box.

**Comment by dsblank** [comment]
@willingc What would you like to do with this PR?

**Comment by willingc** [comment]
@dsblank I'm going to go ahead and close this for now. We can always pick back up at a later date.

**Pull request closed without merging**
