### PR TITLE
Setting up skeleton for Bookdown

### PR DESCRIPTION
**Pull request by tgeorgeux**
If we're sure we want to use Bookdown, this will give us a starting point.

### CODE REVIEW

**Comment by kyleniemeyer** [comment]
We already have a LICENSE.md file, can you remove `LICENSE`?

**Comment by tgeorgeux** [comment]
@kyleniemeyer done.

**Comment by kyleniemeyer** [comment]
@tgeorgeux thanks!

I wonder if we should use a branch for this, in case we decide not to go forward with bookdown. That way we can try it out and see what it looks like without bringing to master.

**Comment by tgeorgeux** [comment]
@kyleniemeyer maybe my Github-fu isn't strong enough, but I don't believe I can add new branches w/o write access. Do you mind opening a 'bookdown' branch for me?

**Comment by kyleniemeyer** [comment]
Done! (Though I think we all have commit/write access by default.)

**Comment by kyleniemeyer** [comment]
Merged into `bookdown`!

**Comment by kyleniemeyer** [comment]
Gonna close this now.

**Pull request closed without merging**
