### PR TITLE
Update Contributing Guide

### LINKED ISSUE #72: Expand CONTRIBUTING.md
We need to say how contributors will be acknowledged. E.g., we could have a list of contributors, updated with certain frequency. If someone contributes a personal anecdote, their name is included in signature after the block-quote. If someone has a large piece to contribute and thinks they would like to be added to the author list, they will have to request this.

Let's discuss process and other contributing conditions, like accepting the license, etc.

### PR DESCRIPTION
**Pull request by willingc**
Closes #72

@dsblank Just realized our PRs may have crossed. Let's review each others and then merge yours. I'll adapt mine to your style.

### CODE REVIEW

**Comment by dsblank** [comment]
Ok, thanks!

**Comment by dsblank** [comment]
Luckily, we focused on different things, mostly. So combined, this is great!

**Comment by willingc** [comment]
Agreed @dsblank! Thank you for doing the parts that I didn't ;-)

**Comment by willingc** [comment]
Teamwork for the win! Thanks @dsblank

**Pull request merged**
