### PR TITLE
change pdf font to palatino

### LINKED ISSUE #98: Determine font for PDF
This issue is a follow-up from discussion on PR #94. 

The current font setting for the PDF does not render/support Unicode well. Should we change fonts or avoid Unicode characters? These are questions that to discuss in this issue.

[Jed's comment](https://github.com/jupyter4edu/jupyter-edu-book/pull/94#discussion_r238419333) and other responses provide additional insights.

### PR DESCRIPTION
**Pull request by willingc**
Although more styling could be done, this PR changes the PDF font to Palatino.

Closes #98

### CODE REVIEW

**Comment by moorepants** [comment]
Looks like you will need to install the latex package:
```
Error: Failed to compile jupyter-edu-book.tex. See jupyter-edu-book.log for more info.
In addition: Warning message:
In parse_packages(logfile, quiet = c(TRUE, FALSE, FALSE)) :
  Failed to find a package that contains Palatino[.](tfm|afm|mf|otf)
Execution halted
The command "./_build.sh" exited with 1.
```

**Comment by moorepants** [comment]
> The TTF/OTF (as in the error message, not Type-1) because we are using XeTeX.

No idea what any of that means :)

**Comment by jedbrown** [comment]
XeTeX is unicode-aware TeX, and uses a newer font format like most other modern software.

**Comment by willingc** [comment]
Closing this. Thanks @jedbrown for the PR and @moorepants for confirming that these settings can often be a mystery :wink:

**Pull request closed without merging**
